// Writes the landing page's QR codes into index.html as data: URLs.
//
//   node tools/qr-inline.mjs [--check]
//
// index.html is served by GitHub Pages and links to each build with a RELATIVE
// href, which is right for a click and useless to a phone camera. The QR beside
// each button carries the absolute URL instead, so the page can be pointed at
// from across a room.
//
// INLINE, as a data: URL, because the alternative is two more files in the repo
// root that have to be regenerated by hand whenever a URL moves, and a landing
// page that 404s a QR if either is forgotten. The source of truth is the URL
// table below; `--check` re-derives both codes and fails if the file has
// drifted from it, so a stale QR is a failing command rather than a wrong link
// nobody notices.
//
// SVG, not PNG: a QR is a grid of squares, which is what a vector is good at.
// It stays crisp at any size, it survives a device-pixel-ratio the PNG was not
// rendered for, and url-encoded it is smaller than the base64 of the same image
// (2.5 KB against 3.4 KB here). shape-rendering=crispEdges is on the root so no
// renderer antialiases a module edge into grey.
import QRCode from "qrcode";
import { readFileSync, writeFileSync } from "fs";

const PAGE = "index.html";
const BASE = "https://joseprio.github.io/color-alchemy/";
// id -> the absolute URL its QR encodes. The id is what ties a code to its
// <img> in the page, so renaming one here renames it there.
const LINKS = {
  bundle: BASE + "dist/bundle.html",
  director: BASE + "dist/director.html",
};

// Dark modules on a light tile, which is the pairing every scanner is built
// for: a QR inverted against a dark page reads as noise to half of them. #001
// is the page's own ink rather than pure black, so the tile sits in the palette
// without pretending to be part of the card.
const svgOf = (text) =>
  QRCode.toString(text, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 3,               // the quiet zone, in modules, and it is not optional
    color: { dark: "#001122ff", light: "#eef6ffff" },
  });

// A data: URL wants the SVG url-encoded, not base64: the payload is text, and
// base64 would cost a third more for nothing. Only the characters that would
// end the attribute or confuse the parser are escaped.
//
// The library already puts shape-rendering on the root, so this only adds one
// if a future version stops doing it — a second copy of the attribute is
// harmless to a renderer and a lie to a reader.
const dataUrl = (svg) => {
  let s = svg.replace(/<\?xml[^>]*\?>\s*/, "").replace(/\s+/g, " ").trim();
  if (!/\bshape-rendering=/.test(s)) s = s.replace(/<svg /, '<svg shape-rendering="crispEdges" ');
  return "data:image/svg+xml," + encodeURIComponent(s);
};

const check = process.argv.includes("--check");
let page = readFileSync(PAGE, "utf8");
let changed = 0, stale = [];

for (const [id, url] of Object.entries(LINKS)) {
  const want = dataUrl(await svgOf(url));
  // the <img> is found by its data-qr id, so neither the layout around it nor
  // the order of the two cards matters here
  const re = new RegExp(`(<img[^>]*\\bdata-qr="${id}"[^>]*\\bsrc=")[^"]*(")`);
  if (!re.test(page)) {
    console.error(`qr-inline: no <img data-qr="${id}"> in ${PAGE}`);
    process.exit(1);
  }
  const before = page;
  page = page.replace(re, `$1${want}$2`);
  if (page !== before) { changed++; stale.push(id); }
  const mods = (await QRCode.create(url, { errorCorrectionLevel: "M" })).modules.size;
  console.log(`qr-inline: ${id} -> ${url}`);
  console.log(`           ${mods}x${mods} modules, ${want.length} chars of data: URL`);
}

if (check) {
  if (changed) {
    console.error(`qr-inline: STALE — ${stale.join(", ")} does not match the URL table. ` +
      "Re-run without --check to rewrite.");
    process.exit(1);
  }
  console.log("qr-inline: both codes match the URL table");
} else if (changed) {
  writeFileSync(PAGE, page);
  console.log(`qr-inline: rewrote ${changed} code(s) in ${PAGE}`);
} else {
  console.log(`qr-inline: ${PAGE} already current`);
}
